version: '3'
services:

    #PHP service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        tty: true

    #node service
    node:
        build:
            context: .
            target: node
        volumes:
            - .:/usr/src
            - ./node_modules:/usr/src/node_modules
        tty: true

    #phpmyadmin + database
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8090:80'
        environment:
            - PMA_HOST=db
        depends_on:
            - db
        tty: true

    db:
        image: mysql:latest
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        tty: true
            